#############   base config   ##############
server:
  port: 11002
#############   Configuration for database   ##############
spring:
  datasource:
    username: zhnf
    password: zhnf@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.121:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    hikari:
      minimum-idle: 8
      maximum-pool-size: 15
      idle-timeout: 240000
      max-lifetime: 300000
      connection-timeout: 60000
      validation-timeout: 5000
      leak-detection-threshold: 60000


mybatis-plus:
  #  SQL语句打印配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    默认值 true
    #      是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN 到经典 Java 属性名 aColumn 的类似映射,
    #      此属性在 mybatis 中原默认值为 false 在 mybatis-plus 中,此属性也将用于生成最终的 sql 的 select body 符合规则无需使用 @TableField 注解指定数据库字段名.
    map-underscore-to-camel-case: true
    #    全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true。
    cache-enabled: true
    #    MyBatis 自动映射时未知列或未知属性处理策略，通过该配置可指定 MyBatis 在自动映射过程中遇到未知列或者未知属性时如何处理，总共有 3 种可选值：
    # AutoMappingUnknownColumnBehavior.NONE：不做任何处理 (默认值)
    # AutoMappingUnknownColumnBehavior.WARNING：以日志的形式打印相关警告信息
    # AutoMappingUnknownColumnBehavior.FAILING：当作映射失败处理，并抛出异常和详细信息
    auto-mapping-unknown-column-behavior: none
  global-config:
    field-strategy: 1
    db-config:
      #      逻辑已删除值,(逻辑删除下有效),默认值1
      logic-delete-value: 1
      #      逻辑未删除值,(逻辑删除下有效),默认值0
      logic-not-delete-value: 0
      #      全局逻辑删除字段值，不是数据库的字段名称，而是实体类里面的名称
      logic-delete-field: isDelete
      #      表名前缀,默认null
      table-prefix:
      #        表名、是否使用下划线命名，默认数据库表使用下划线命名,默认true
      table-underline: true
      #      全局默认主键类型,默认值：ID_WORKER
      id-type: auto
      #      是否开启大写命名，默认不开启。默认true
      capital-mode: true
  #    TypeHandler 扫描路径，如果配置了该属性，SqlSessionFactoryBean 会把该包下面的类注册为对应的 TypeHandler,默认null
  type-handlers-package: com.example.mpd.mapper.handler
  #  枚举类 扫描路径，如果配置了该属性，会将路径下的枚举类进行注入，让实体类字段能够简单快捷的使用枚举属性，具体使用请结合 枚举注入 查看 ,默认null
  type-enums-package: com.example.mpd.enums


